CREATE TABLE schedule (
  user_id INTEGER REFERENCES users("UserID") ON DELETE CASCADE,
  course_id INTEGER REFERENCES courses(course_id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, course_id)
);

CREATE TABLE courses (
  "course_id" SERIAL PRIMARY KEY,
  "CRN" TEXT,
  "TERM" TEXT,
  "Department" TEXT,
  "Subject" TEXT,
  "Course" TEXT,
  "Section" TEXT,
	"Title" TEXT,
  "Schedule_Type" TEXT,
  "Grade_Mode" TEXT,
  "Special_Permission_To_Enroll" TEXT,
  "Part_Of_Term" TEXT,
  "Credit_Hours" TEXT,
  "Billing_Hours" TEXT,
  "Viewable_On_Vision" TEXT,
  "Max_Enrollment" TEXT,
  "Classroom_Capacity" TEXT,
  "Enrolled" TEXT,
  "Registration_Complete" TEXT,
  "Virtual_Only" TEXT,
  "Start_Date" TEXT,
  "End_Date" TEXT,
  "Days" TEXT,
  "Meeting_Time" TEXT,
  "Classroom" TEXT,
  "Meeting_Time_Instructor" TEXT,
  "Primary_Instructor" TEXT,
  "Course_fees" TEXT,
  "Prerequisites" TEXT,
  "Corequisites" TEXT,
  "Crosslisted_Sections" TEXT,
  "RES_DEPT" TEXT,
  "RES_FIELD_OF_STUDY" TEXT,
  "RES_CLASS" TEXT,
  "RES_LEVEL" TEXT,
  "RES_DEGREE" TEXT,
  "RES_PROGRAM" TEXT,
  "RES_CAMPUS" TEXT,
  "RES_COLLEGE" TEXT,
  "RES_STUDENT_ATTRIBUTES" TEXT,
  "RES_COHORT" TEXT,
  "syllabus_id" TEXT,
)

CREATE TABLE courses (
  "CRN" TEXT,
  "TERM" TEXT,
  "Department" TEXT,
  "Subject" TEXT,
  "Course" TEXT,
  "Section" TEXT,
	"Title" TEXT,
  "Schedule_Type" TEXT,
  "Grade_Mode" TEXT,
  "Special_Permission_To_Enroll" TEXT,
  "Part_Of_Term" TEXT,
  "Credit_Hours" TEXT,
  "Billing_Hours" TEXT,
  "Viewable_On_Vision" TEXT,
  "Max_Enrollment" TEXT,
  "Classroom_Capacity" TEXT,
  "Enrolled" TEXT,
  "Registration_Complete" TEXT,
  "Virtual_Only" TEXT,
  "Start_Date" TEXT,
  "End_Date" TEXT,
  "Days" TEXT,
  "Meeting_Time" TEXT,
  "Classroom" TEXT,
  "Meeting_Time_Instructor" TEXT,
  "Primary_Instructor" TEXT,
  "Course_fees" TEXT,
  "Prerequisites" TEXT,
  "Corequisites" TEXT,
  "Crosslisted_Sections" TEXT,
  "RES_DEPT" TEXT,
  "RES_FIELD_OF_STUDY" TEXT,
  "RES_CLASS" TEXT,
  "RES_LEVEL" TEXT,
  "RES_DEGREE" TEXT,
  "RES_PROGRAM" TEXT,
  "RES_CAMPUS" TEXT,
  "RES_COLLEGE" TEXT,
  "RES_STUDENT_ATTRIBUTES" TEXT,
  "RES_COHORT" TEXT
)

CREATE TABLE public.users (
    "UserID" SERIAL PRIMARY KEY,
    "Email" character varying(100), UNIQUE
    "Password" character varying(100),
    "FirstName" text,
    "LastName" text,
    "Department" text,
    "UserRole" text,
    "reset_code" text,
    "reset_code_expires" timestamptz,
);
